<?php

return [
    'brand' => [
        'name' => 'Departemen Teknologi Multimedia Kreatif',
        'short_name' => 'DTMK',
        'institution' => 'Politeknik Elektronika Negeri Surabaya',
        'email' => 'dtmk@pens.ac.id',
        'address' => 'Kampus PENS, Jl. Raya ITS, Keputih, Sukolilo, Surabaya, Jawa Timur 60111',
    ],

    'navigation' => [
        ['label' => 'Beranda', 'href' => '#beranda'],
        ['label' => 'Tentang', 'href' => '#tentang'],
        ['label' => 'Program Studi', 'href' => '#program-studi'],
        ['label' => 'Portal Aplikasi', 'href' => '#portal-aplikasi'],
        ['label' => 'Teaching Factory', 'href' => '#teaching-factory'],
        ['label' => 'Riset & Karya', 'href' => '#riset-karya'],
        ['label' => 'Mitra', 'href' => '#mitra'],
        ['label' => 'Kontak', 'href' => '#kontak'],
    ],

    'stats' => [
        ['value' => '4', 'label' => 'Program Studi'],
        ['value' => '10', 'label' => 'Portal Akademik'],
        ['value' => '6', 'label' => 'Klaster Riset'],
    ],

    'highlights' => [
        [
            'title' => 'OBE',
            'description' => 'Perancangan capaian pembelajaran, asesmen, dan evaluasi kurikulum berbasis outcome.',
            'icon' => 'target',
            'url' => '#portal-aplikasi',
            'status' => 'active',
        ],
        [
            'title' => 'Project-Based Learning',
            'description' => 'Mahasiswa mengerjakan proyek riil lintas multimedia, game, media interaktif, dan bisnis digital.',
            'icon' => 'project',
            'url' => '#teaching-factory',
            'status' => 'active',
        ],
        [
            'title' => 'Teaching Factory',
            'description' => 'Model produksi vokasi yang menghubungkan kelas, studio, laboratorium, dan kebutuhan mitra.',
            'icon' => 'factory',
            'url' => '#teaching-factory',
            'status' => 'active',
        ],
        [
            'title' => 'Industri Kreatif',
            'description' => 'Kolaborasi dengan studio, agensi, startup, broadcaster, dan mitra produk digital.',
            'icon' => 'handshake',
            'url' => '#mitra',
            'status' => 'active',
        ],
        [
            'title' => 'Digital Media',
            'description' => 'Ekosistem produksi konten, pengalaman interaktif, distribusi digital, dan analitik media.',
            'icon' => 'media',
            'url' => '#riset-karya',
            'status' => 'active',
        ],
    ],

    'programs' => [
        [
            'title' => 'D3 Teknologi Multimedia dan Broadcasting',
            'description' => 'Program vokasi untuk produksi multimedia, broadcast digital, siniar, studio, dan konten lintas platform.',
            'icon' => 'broadcast',
            'url' => 'https://mmb.pens.ac.id',
            'status' => 'active',
            'meta' => 'MMB',
        ],
        [
            'title' => 'Sarjana Terapan Teknologi Game',
            'description' => 'Pembelajaran game design, game programming, visual asset, simulasi, dan produksi game berbasis industri.',
            'icon' => 'gamepad',
            'url' => 'https://gametech.pens.ac.id',
            'status' => 'active',
            'meta' => 'Game Technology',
        ],
        [
            'title' => 'Sarjana Terapan Teknologi Rekayasa Multimedia',
            'description' => 'Fokus pada rekayasa sistem multimedia, AR/VR/XR, media interaktif, UI/UX, dan integrasi teknologi kreatif.',
            'icon' => 'cube',
            'url' => 'https://trm.pens.ac.id',
            'status' => 'active',
            'meta' => 'TRM',
        ],
        [
            'title' => 'Bisnis Digital',
            'description' => 'Mengembangkan talenta produk digital, strategi bisnis, pemasaran kreatif, analitik, dan kewirausahaan teknologi.',
            'icon' => 'briefcase',
            'url' => 'https://digibiz.pens.ac.id',
            'status' => 'active',
            'meta' => 'Digital Business',
        ],
    ],

    'applications' => [
        [
            'title' => 'Kurikulum OBE',
            'description' => 'Pemetaan profil lulusan, CPL, bahan kajian, mata kuliah, dan struktur kurikulum.',
            'icon' => 'route',
            'url' => 'https://kurikulum.dtmkpens.id',
            'status' => 'active',
        ],
        [
            'title' => 'RPS & CPMK',
            'description' => 'Manajemen RPS, CPMK, sub-CPMK, materi pembelajaran, dan rencana evaluasi.',
            'icon' => 'file',
            'url' => 'https://rps.dtmkpens.id',
            'status' => 'active',
        ],
        [
            'title' => 'Assessment CPL',
            'description' => 'Pemantauan ketercapaian CPL, rubrik asesmen, portofolio bukti, dan evaluasi outcome.',
            'icon' => 'target',
            'url' => 'https://assessment.dtmkpens.id',
            'status' => 'development',
        ],
        [
            'title' => 'Tracer Study',
            'description' => 'Survei lulusan, masukan pengguna alumni, data serapan kerja, dan insight peningkatan mutu.',
            'icon' => 'users',
            'url' => 'https://tracer.dtmkpens.id',
            'status' => 'development',
        ],
        [
            'title' => 'Teaching Factory / PBL',
            'description' => 'Pengelolaan brief industri, tim mahasiswa, milestone produksi, rubrik, dan keluaran produk.',
            'icon' => 'factory',
            'url' => 'https://tefa.dtmkpens.id',
            'status' => 'active',
        ],
        [
            'title' => 'Repository Karya Mahasiswa',
            'description' => 'Etalase karya, portfolio, demo produk, dokumentasi proyek, dan publikasi kreativitas mahasiswa.',
            'icon' => 'folder',
            'url' => 'https://portfolio.dtmkpens.id',
            'status' => 'active',
        ],
        [
            'title' => 'Jadwal Studio / Lab',
            'description' => 'Reservasi ruang, jadwal studio, penggunaan laboratorium, dan ketersediaan fasilitas produksi.',
            'icon' => 'calendar',
            'url' => 'https://studio.dtmkpens.id',
            'status' => 'development',
        ],
        [
            'title' => 'Podcast / Siniar',
            'description' => 'Publikasi episode, produksi audio, arsip konten, dan kanal siniar departemen.',
            'icon' => 'microphone',
            'url' => 'https://siniar.dtmkpens.id',
            'status' => 'planned',
        ],
        [
            'title' => 'Kerja Praktik / Magang',
            'description' => 'Administrasi KP, magang industri, pembimbingan, laporan, dan evaluasi mitra.',
            'icon' => 'handshake',
            'url' => 'https://kp.dtmkpens.id',
            'status' => 'development',
        ],
        [
            'title' => 'Admin Portal',
            'description' => 'Konsol operator untuk mengelola konten, data akademik, akses aplikasi, dan integrasi layanan.',
            'icon' => 'lock',
            'url' => 'https://admin.dtmkpens.id',
            'status' => 'active',
        ],
    ],

    'factory_flow' => [
        'Industri / Mitra',
        'Project Brief',
        'Produksi Mahasiswa',
        'Evaluasi Rubrik',
        'Portfolio',
        'Hilirisasi Produk',
    ],

    'research' => [
        [
            'title' => 'Multimedia Production',
            'description' => 'Produksi visual, audio, video, studio virtual, storytelling, dan konten lintas kanal.',
            'icon' => 'media',
            'url' => '#riset-karya',
            'status' => 'active',
        ],
        [
            'title' => 'Game Technology',
            'description' => 'Game engine, gameplay systems, serious game, gamifikasi, simulasi, dan asset pipeline.',
            'icon' => 'gamepad',
            'url' => '#riset-karya',
            'status' => 'active',
        ],
        [
            'title' => 'AR/VR/XR',
            'description' => 'Pengalaman imersif, spatial interaction, virtual production, pelatihan, dan simulasi digital.',
            'icon' => 'cube',
            'url' => '#riset-karya',
            'status' => 'development',
        ],
        [
            'title' => 'Digital Broadcasting',
            'description' => 'Streaming, siniar, siaran digital, sistem studio, produksi live, dan distribusi konten.',
            'icon' => 'broadcast',
            'url' => '#riset-karya',
            'status' => 'active',
        ],
        [
            'title' => 'UI/UX & Interactive Media',
            'description' => 'Riset pengguna, desain antarmuka, prototyping, pengalaman interaktif, dan evaluasi usability.',
            'icon' => 'palette',
            'url' => '#riset-karya',
            'status' => 'active',
        ],
        [
            'title' => 'Digital Business',
            'description' => 'Produk digital, model bisnis, pemasaran kreatif, data insight, dan komersialisasi karya.',
            'icon' => 'chart',
            'url' => '#riset-karya',
            'status' => 'planned',
        ],
    ],

    'partners' => [
        [
            'title' => 'Creative Studio',
            'description' => 'Mitra produksi multimedia dan konten kreatif.',
            'icon' => 'spark',
            'url' => '#kontak',
            'status' => 'planned',
        ],
        [
            'title' => 'Game Studio',
            'description' => 'Mitra pengembangan game, simulasi, dan gamifikasi.',
            'icon' => 'gamepad',
            'url' => '#kontak',
            'status' => 'planned',
        ],
        [
            'title' => 'Broadcast Network',
            'description' => 'Mitra siaran, streaming, studio, dan media digital.',
            'icon' => 'broadcast',
            'url' => '#kontak',
            'status' => 'planned',
        ],
        [
            'title' => 'Digital Startup',
            'description' => 'Mitra produk digital, analitik, dan inovasi bisnis.',
            'icon' => 'briefcase',
            'url' => '#kontak',
            'status' => 'planned',
        ],
        [
            'title' => 'XR Lab',
            'description' => 'Mitra pengalaman imersif, virtual production, dan simulasi.',
            'icon' => 'cube',
            'url' => '#kontak',
            'status' => 'planned',
        ],
        [
            'title' => 'Industry Mentor',
            'description' => 'Mitra mentor proyek, rubrik evaluasi, dan hilirisasi.',
            'icon' => 'handshake',
            'url' => '#kontak',
            'status' => 'planned',
        ],
    ],

    'social_links' => [
        ['label' => 'Instagram', 'href' => '#'],
        ['label' => 'YouTube', 'href' => '#'],
        ['label' => 'LinkedIn', 'href' => '#'],
    ],
];
